on:
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - xmake.lua
  pull_request:
    paths:
      - .github/workflows/build.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -w -y

      - run: |
          xmake package -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: preloader-windows-x64-${{ github.sha }}
          path: |
            build/packages/p/preloader/windows/x64/release/

  check-style:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          Get-ChildItem src/ -Filter *.cpp -Recurse | ForEach-Object { clang-format --dry-run -Werror $_.FullName; if ($LASTEXITCODE -ne 0) { exit 1; } }
          Get-ChildItem src/ -Filter *.h -Recurse | ForEach-Object { clang-format --dry-run -Werror $_.FullName; if ($LASTEXITCODE -ne 0) { exit 1; } }
